using RadiCorder.Hosting;
using System.Globalization;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.Extensions.FileProviders;
using RadiCorder.Application;
using RadiCorder.DependencyInjection;
using RadiCorder.Logics.Infrastructure.Recording;
using RadiCorder.Logics.Logics;
using RadiCorder.Logics.RdbContext;
using RadiCorder.Logics.Services;
using ZLogger;


CultureInfo.DefaultThreadCurrentCulture = new CultureInfo("ja-JP");
// 時間帯を日本時間に設定

var builder = WebApplication.CreateBuilder(args);
var localSettingsPath = Path.Combine(builder.Environment.ContentRootPath, "radicorder.settings.json");
var systemSettingsPath = "/etc/radicorder/radicorder.settings.json";
var autoGeneratedSettingsPath = LinuxSettingsFileInitializer.EnsureLinuxSettingsFile(localSettingsPath, systemSettingsPath, builder.Environment.ContentRootPath);

if (OperatingSystem.IsLinux())
{
    builder.Host.UseSystemd();
}

// Add services to the container.
builder.Services.AddControllersWithViews();

// Configuration
var config = builder.Configuration;
config.AddJsonFile("radicorder.settings.json", optional: true, reloadOnChange: true);
config.AddJsonFile("/etc/radicorder/radicorder.settings.json", optional: true, reloadOnChange: true);
config.AddEnvironmentVariables();

// DB
builder.Services.AddDbDi(config, builder.Environment);

// Options
builder.Services.AddConfigDi(config);

// Logger
builder.Logging.AddLoggingDi(config);

// DataProtection
{
    var dataProtectionBuilder = builder.Services.AddDataProtection();

    if (!OperatingSystem.IsWindows())
    {
        var keysPath = config["RadiCorder:DataProtectionKeysPath"];
        if (string.IsNullOrWhiteSpace(keysPath))
        {
            keysPath = Path.Combine(builder.Environment.ContentRootPath, "keys");
        }

        Directory.CreateDirectory(keysPath);
        dataProtectionBuilder.PersistKeysToFileSystem(new DirectoryInfo(keysPath));
    }
}

// ServiceCollection
builder.Services.AddLogicDiCollection(config);

// for API
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddOpenApi();
builder.Services.AddSignalR();


var app = builder.Build();
if (!string.IsNullOrWhiteSpace(autoGeneratedSettingsPath))
{
    app.Logger.ZLogInformation($"設定ファイルが見つからなかったため、既定値で自動生成しました。 path={autoGeneratedSettingsPath}");
}

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Home/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

using (var scope = app.Services.CreateScope())
{
    var context = scope.ServiceProvider.GetRequiredService<RadioDbContext>();
    await DatabaseInitializer.ApplyMigrationsWithBackupIfNeededAsync(context, app.Environment.ContentRootPath, app.Logger);
}

app.UseStaticFiles();

// HLS形式ファイル保存先
{
    // DIで格納したRadikoOptionsを取得
    var appConfigService = app.Services.GetRequiredService<IAppConfigurationService>();
    var hlsCacheRoot = TemporaryStoragePaths.GetHlsCacheRootDirectory(appConfigService.TemporaryFileSaveDir);
    Directory.CreateDirectory(hlsCacheRoot);

    app.UseStaticFiles(new StaticFileOptions
    {
        FileProvider = new PhysicalFileProvider(hlsCacheRoot),
        RequestPath = "/static"
    });
}

app.UseRouting();

app.UseAuthorization();
app.UseAntiforgery();

app.UseMiddleware<RequestLoggingScopeMiddleware>();

if (app.Environment.IsDevelopment())
{
    app.UseMemoryUsageMiddleware();
}

#pragma warning disable ASP0014
app.UseEndpoints(endpoints =>
{
    endpoints.MapRadiCorderEndpoints();
});
#pragma warning restore ASP0014

if (app.Environment.IsDevelopment())
{
    app.MapOpenApi();

    // TypeScriptマップ用
    app.UseFileServer(new FileServerOptions()
    {
        FileProvider = new PhysicalFileProvider(Path.Combine(app.Environment.ContentRootPath, "Scripts")),
        RequestPath = new PathString("/Scripts"),
    });
}


using (var scope = app.Services.CreateScope())
{
    var startupTask = scope.ServiceProvider.GetRequiredService<StartupTask>();
    await startupTask.InitializeAsync();
}

var localApplicationUrlService = app.Services.GetRequiredService<ILocalApplicationUrlService>();
localApplicationUrlService.SetCandidateUrls(app.Urls);
app.Lifetime.ApplicationStarted.Register(() =>
{
    localApplicationUrlService.SetCandidateUrls(app.Urls);
});

// Windows インストーラー（Inno Setup / WinGet）がアップグレード時に実行中を検出できるよう
// Mutex をプロセス存続中だけ保持する。多重起動の制御はHTTPポートバインドに委ねる。
using var appMutex = OperatingSystem.IsWindows()
    ? new Mutex(false, "RadiCorderRunningMutex")
    : null;

app.Run();

