#!/bin/sh
set -e

. /usr/share/debconf/confmodule
db_version 2.0 || true
db_capb backup || true

db_input high radicorder/port || true
db_input high radicorder/record_dir || true
db_input high radicorder/temp_dir || true
db_go || true

exit 0
